% todo[doc]
function IntrinsicsH = TL_PhysicalParamsToIntrins( PhysicalParams )

% PhysicalParams

%---
% Extract variables from struct for convenience
[Fsx,Fsy,Fux,Fuy,csx,csy,cux,cuy,du,fMx,fMy,dM, LFSize, ResampRate] = ...
	LFStruct2Var( PhysicalParams, 'Fsx','Fsy','Fux','Fuy','csx','csy','cux','cuy','du','fMx','fMy','dM', 'LFSize','ResampRate' );
%---

% resampling during the decode has changed the effective sample rates, correct here
Fsx = Fsx * ResampRate(1);
Fsy = Fsy * ResampRate(2);
Fux = Fux * ResampRate(3);
Fuy = Fuy * ResampRate(4);

% Pixel order on sensor is flipped in both x and y relative to our s,t and u,v coordinate systems
H_sensor_orientation = [...
	-1,     0,      0,      0,      LFSize(2)+1;
	0,     -1,      0,      0,      LFSize(1)+1;
	0,      0,     -1,      0,      LFSize(4)+1;
	0,      0,      0,     -1,      LFSize(3)+1;
	0,      0,      0,      0,      1;];

% Relative pixel coordinates (i,j) and lenslet centres (k,l) in pixels -> meters
H_abs_to_phi = [ ...
	1/Fsx,  0,      1/Fux,  0,        -csx/Fsx - cux/Fux;   ...
	0,      1/Fsy,  0,      1/Fuy,    -csy/Fsy - cuy/Fuy;   ...
	0,      0,      1/Fux,  0,        -cux/Fux;  ...
	0,      0,      0,      1/Fuy,    -cuy/Fuy;  ...
	0,      0,      0,      0,        1 ];

% Absolute to relative direction
H_phi_to_rel = [ ...
	1,0,        0,0,     0;   ...
	0,1,        0,0,     0;   ...
	-1/du,0,    1/du,0,  0;   ...
	0,-1/du,    0,1/du,  0;   ...
	0,0,        0,0,     1];

% Propagate to main lens
H_to_main = [ ...
	1,0,    du+dM,0,     0;  ...
	0,1,    0,du+dM,     0;  ...
	0,0,    1,0,         0;  ...
	0,0,    0,1,         0;  ...
	0,0,    0,0,         1];

% Refract at main lens
H_main = [ ...
	1,0,        0,0,         0;  ...
	0,1,        0,0,         0;  ...
	-1/fMx,0,   1,0,         0;  ...
	0,-1/fMy,   0,1,         0;  ...
	0,0,        0,0,         1];

IntrinsicsH = H_main * H_to_main * H_phi_to_rel * H_abs_to_phi * H_sensor_orientation;

% The main lens principal axis defines the coordinate system, so that decentering terms are relative
% to that.

% todo: recenter?
% IntrinsicsH = LFRecenterIntrinsics( IntrinsicsH, LFSize );


